### PR TITLE
requirements: Add pynetbox to cPanel and hPanel repo

### PR DESCRIPTION
**Pull request by paumic**
Adding required module for NetBox ansible role.

### CODE REVIEW

**Comment by v1tal1s** [comment]
@paumic please add also to :) 
[ansible_ovzcloud.txt](https://github.com/hostinger/awx/blob/04e6fe8c67a332abdcb2a20cd5c9561dfe5313cf/requirements/hostinger/ansible_ovzcloud.txt)
[ansible_cloud.txt](https://github.com/hostinger/awx/blob/04e6fe8c67a332abdcb2a20cd5c9561dfe5313cf/requirements/hostinger/ansible_cloud.txt)
[ansible_infra.txt](https://github.com/hostinger/awx/blob/04e6fe8c67a332abdcb2a20cd5c9561dfe5313cf/requirements/hostinger/ansible_infra.txt)

**Comment by paumic** [comment]
Added 👏

**Review by dominykasn — APPROVED** [review]
build the image in jenkins afterwards, thanks

**Comment by paumic** [comment]
don't know how to, please build it or ask sae-infra to do so.

**Pull request merged**
